version: '3.9'

services:
  postgres:
    image: postgres
    container_name: EventsManagementdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Eventsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - eventnet

volumes:
  pgdata:

networks:
  eventnet:
    driver: bridge